name: Build and deploy Jekyll site to Cloudflare Pages

on:
  push:
    branches:
      - master

jobs:
  cloudflare-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
            
      - name: Build Jekyll 
        uses: helaili/jekyll-action@2.5.0
        with:
          # The GITHUB_TOKEN secret
          token: ${{ github.token }}
          # The Jekyll environment to build
          jekyll_env: development
          # The Jekyll website source directory
          jekyll_src: ./
           # The Jekyll Gemfile directory
          gem_src: ./
          build_only: true
          # The target branch name the site gets pushed to
          target_branch: none
          # Additional Jekyll build arguments (see https://jekyllrb.com/docs/configuration/options/#build-command-options)
          # jekyll_build_options: # optional
          # The relative path where the site gets pushed to
          #target_path: # optional
          # Will build the Jekyll site without publishing it
          #build_only: # optional
          # The directory to build your project in
          #build_dir: # optional
          # Do not overwrite whatever was already published on the target branch
          keep_history: false
          build_dir: _site
          # Commands to run prior to build and deploy. Useful for ensuring build dependencies are up to date or installing  new dependencies. For example, use `apk --update add  imagemagick` to install ImageMagick.
          #pre_build_commands: # optional
          # When set override the default bundler version provided.
          #bundler_version: # optional
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3.1.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy _site --project-name=atelie-zhmayeva --commit-dirty=true --skip-caching

      - name: Purge Cloudflare HTML cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{
            "files": [
              "https://zhmayeva.com/",
              "https://www.zhmayeva.com/"
            ]
          }'
      
